### ISSUE TITLE
Cocoapod rating still taking heat for poor documentation :(

### ISSUE THREAD

**Issue by LunaCodeGirl** [justinvallely/SwiftPhotoGallery#23]
Much better than before though! 

![](https://www.evernote.com/l/AAXSGkvGpLRAFIpfwJzClfSqhc052KEIbtcB/image.png)

( _saw the activity on this repo and figured I had to heckle you a little_ 😏 )

**Comment by justinvallely** [comment]
Cocoapod rating taking heat for open issues. Closing now that you got your heckles in. 😄
