### ISSUE TITLE
Current podspec is out of sync with documentation

### ISSUE THREAD

**Issue by keyboardsamurai** [justinvallely/SwiftPhotoGallery#26]
Both `pageIndicatorTintColor` and `currentPageIndicatorTintColor` that are used in the documentation examples are currently only available on the git HEAD, but not in the podspec version. The current workaround is to use something like

`pod "SwiftPhotoGallery", :git => 'https://github.com/Inspirato/SwiftPhotoGallery', :commit => 'e9b670e'`

**Comment by justinvallely** [comment]
Make sure you run `pod install` to get the latest version. Everything looks good on my end.
