### ISSUE TITLE
GPLv3 exception is needed for 3rd parties to distribute on the App Store

### ISSUE THREAD

**Issue by chrisballinger** [justinvallely/SwiftPhotoGallery#42]
For more information about why this is required, please read this blog post: https://whispersystems.org/blog/license-update/

Here is how they resolved the issue:

> Additional Permissions For Submission to Apple App Store: Provided that you are otherwise in compliance with the GPLv3 for each covered work you convey (including without limitation making the Corresponding Source available in compliance with Section 6 of the GPLv3), Open Whisper Systems also grants you the additional permission to convey through the Apple App Store non-source executable versions of the Program as incorporated into each applicable covered work as Executable Versions only under the Mozilla Public License version 2.0 (https://www.mozilla.org/en-US/MPL/2.0/).

**Comment by justinvallely** [comment]
Can you please explain in more detail, the problem you're having? I distribute apps on the app store with this framework using the license as is without any problems.

**Comment by chrisballinger** [comment]
Due to a conflict with the GPL and the App Store terms, the license is void when distributed via the App Store. This means everyone who is currently distributing this library in their apps is violating the GPL. As the rights holder, if you or your company chose to, you could prosecute every 3rd party developer and force the removal of their apps and claim damages.

Since you're the copyright owner and already have the full rights to the code, you can distribute it on the App Store without issue, because by doing so you're implicitly relicensing it when Apple's restrictions are applied on top. Other developers don't have this right because the GPL explicitly forbids applying additional restrictions.

To solve this, you can either explicitly grant an exception, similar to above, or choose an alternative copyleft license like MPL2. You can also keep it as is, but it means people who do their due diligence won't be able to use it.

Further reading:

* https://arstechnica.com/apple/2011/01/vlc-for-ios-vanishes-2-months-after-eruption-of-gpl-dispute/
* https://arstechnica.com/apple/2013/07/vlc-media-player-returns-to-the-ios-app-store-after-30-month-hiatus/

**Comment by justinvallely** [comment]
Great description, Chris. Thank you. I'm on it.

**Comment by rushk2112** [comment]
I was looking for a simple and quick Photo browser and stumbled across this project but the Licensing issue will prevent me from doing this.

@justinvallely : Will you be updating this in the near future? Thanks!

**Comment by crowell256aa** [comment]
Bumping this to see if there is an update.

**Comment by justinvallely** [comment]
@crowell256aa Waiting for more traction. 2 requests out of 15,000 downloads.

**Comment by chrisballinger** [comment]
@justinvallely Sure, it just means that 14,998 people are possibly illegally redistributing your code in violation of the GPL, and could be sued by you at any time for ridiculous damages. However, having seen my own code ripped off plenty of times, I've learned that lots of people don't care about proper license compliance.. so whatever.

**Comment by justinvallely** [comment]
@chrisballinger Chris - I understand your frustration. I've checked out your work and I'm big fan of what you're all about. Thank you for doing what you do and remaining diligent. Let's find a win-win solution here. I'll message you directly.

**Comment by justinvallely** [comment]
Resolved in version 3.3.1. License is now Apache 2. Thanks @chrisballinger, @crowell256aa.
