### ISSUE TITLE
How does this integrate at all with SDWebImage

### ISSUE THREAD

**Issue by Viktorfalkner** [justinvallely/SwiftPhotoGallery#44]
Your delegate methods need an optional UIImage, however SDWebImage sets an image on an ImageView.

Am I supposed to create a random ImageView and pass back the image I get from SDWebImage?

Or how do I utilize this library with SDWebImage?

**Comment by justinvallely** [comment]
SDWebImage can do more than just set an image on an ImageView. Use the download manager to prefetch the image and then pull the image from SD's image cache using `imageFromDiskCache(forKey:` to add it to SwiftPhotoGallery.

```
let manager: SDWebImageManager = SDWebImageManager.shared()
            manager.downloadImage(with: fullURL, options: [], progress: {(_, _) -> Void in
                // progression tracking code
                }, completed: {(_, _, _, _, _) -> Void in
                    // completion block
            })
```

**Comment by SamDecrock** [comment]
That download block is asynchronously, how can I use it to return a UIImage upon...

```Swift
func imageInGallery(gallery: SwiftPhotoGallery, forIndex: Int) -> UIImage? 
```

?

**Comment by DarkwingXL** [comment]
Is there any example for "Integrates seamlessly with SDWebImage"?

You wrote: "prefetch the image and then pull the image from SD's image cache using imageFromDiskCache(forKey: to add it to SwiftPhotoGallery."
But this is an extremely unsafe way and definitely not seamlessly.

**Comment by CocoaPriest** [comment]
But what's the point writing `Integrates seamlessly with SDWebImage` then? It doesn't really do that at all.
