### ISSUE TITLE
Opening SwiftGallery and changing orientation doesn't work

### ISSUE THREAD

**Issue by Viktorfalkner** [justinvallely/SwiftPhotoGallery#45]
After opening a Gallery, I am encountering 2 problems.

1. In portrait, if there is a large amount of photos, the page control goes outside of the view and looks weird.

2. If I swift the orientation while in the gallery
<img width="510" alt="screen shot 2017-04-06 at 11 11 02 pm" src="https://cloud.githubusercontent.com/assets/7623484/24786431/a41205e0-1b1e-11e7-8213-2d7cd108160b.png">
<img width="303" alt="screen shot 2017-04-06 at 11 10 48 pm" src="https://cloud.githubusercontent.com/assets/7623484/24786430/a410afa6-1b1e-11e7-8081-b80017792342.png">

The pictures go off kilter and don't line up properly and skip.

Is there a way to fix these issues? Love the gallery, just wanted to see if I could touch up a couple things.

**Comment by justinvallely** [comment]
Hi Viktor,

What version of the cocoapod are you using?

**Comment by Viktorfalkner** [comment]
Using SwiftPhotoGallery (3.1.0)

**Comment by justinvallely** [comment]
This bug was fixed in a prior release so I'm surprised to see it still happening. If you wouldn't mind, I'd love to get your help debugging a bit so we can get this fixed. Could you please tell me about how you're instantiating the gallery, what version of Swift you're using, and copy/paste the output of `pod env` here.

**Comment by Viktorfalkner** [comment]
Hey sorry for the abysmally late response. I went on vacation and have been stuck at an airport for days.

I am looking to solve this issue this week, and actually live in Denver, so we can talk on the phone if you'd like.

I'll message you once I make it back to the mainland

**Comment by Viktorfalkner** [comment]
I'm back, we can go over this tomorrow, or Friday if you aren't busy?

**Comment by Viktorfalkner** [comment]
Let me know when you're available to try and solve this issue, I'll be around all day.

**Comment by Viktorfalkner** [comment]
class PropertyDetailsFullScreenViewController: UIViewController {

    lazy var galleryView = SwiftPhotoGallery(coder: NSCoder())
    let xButton = UIButton()
    
    var imageURLStrings:[String]
    
    init(imageURLArray:[String]) {
        self.imageURLStrings = imageURLArray
        
        super.init(nibName: nil, bundle: nil)
    }
    
    required convenience init(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        initializeSubviews()
        applyStyles()
    }

    func initializeSubviews() {
        galleryView = SwiftPhotoGallery(delegate: self, dataSource: self)
        galleryView?.view.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview((galleryView?.view)!)
        
        galleryView?.view.backgroundColor = UIColor.black
//        galleryView?.view.pageIndicatorTintColor = UIColor.grayColor().colorWithAlphaComponent(0.5)
//        galleryView.view..currentPageIndicatorTintColor = UIColor.whiteColor()
        
        
        xButton.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(xButton)
        
        xButton.setImage(#imageLiteral(resourceName: "xMark"), for: .normal)
        xButton.addTarget(self, action: #selector(closeButtonWasPressed), for: .touchUpInside)
    }
    
    
    override func updateViewConstraints() {
        self.view.haveViewFilledBy((galleryView?.view)!)
        
        xButton.widthAnchor.constraint(equalToConstant: 30).isActive = true
        xButton.heightAnchor.constraint(equalToConstant: 30).isActive = true
        xButton.topAnchor.constraint(equalTo: self.view.topAnchor, constant:20).isActive = true
        xButton.rightAnchor.constraint(equalTo: self.view.rightAnchor, constant:-20).isActive = true

        super.updateViewConstraints()
    }
    
    func applyStyles() {
        
    }
    
    func closeButtonWasPressed() {
        self.dismiss(animated: true, completion: nil)
    }

}

extension PropertyDetailsFullScreenViewController: SwiftPhotoGalleryDelegate, SwiftPhotoGalleryDataSource {
    func numberOfImagesInGallery(gallery: SwiftPhotoGallery) -> Int {
        return imageURLStrings.count
    }
    
    func imageInGallery(gallery: SwiftPhotoGallery, forIndex: Int) -> UIImage? {

        if let url = URL(string: imageURLStrings[forIndex]) {
            let data = try? Data.init(contentsOf: url)
            let image = UIImage.sd_image(with: data)
            return image
        }
        
        return nil
    }
    
    func galleryDidTapToClose(gallery: SwiftPhotoGallery) {
        self.dismiss(animated: true, completion: nil)
    }
}

-----
PRINT OUT OF pod env
-----
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1212)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0bbdb35b44add2affbca1eac2c93b3fb4f6b6af9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, ’10.0’

target 'iOS-Core' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    

    pod 'Alamofire'
    pod 'SwiftyJSON', :git => 'https://github.com/appsailor/SwiftyJSON.git', :branch => 'swift3'
    pod 'SWXMLHash'
    pod ‘GEOSwift’
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'Google/SignIn'
    pod 'FacebookLogin'
    pod 'SDWebImage/WebP'
    pod "SwiftPhotoGallery"
    pod 'Firebase'
    pod 'FBAnnotationClusteringSwift', :git => 'https://github.com/ribl/FBAnnotationClusteringSwift.git'
    
    # Pods for iOS-Core
    
    #  target 'iOS-CoreTests' do
    #    inherit! :search_paths
    #    # Pods for testing
    #  end
    #
    #  target 'iOS-CoreUITests' do
    #    inherit! :search_paths
    #    # Pods for testing
    #  end
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```


-----

Thats how I instantiate it.

This gallery is loaded from a "DidSelect" method on a tableView.

All I do is add it to a controller with a X.

Make it fill the screen, and give it images.

-----

The problem only happens when I switch orientations while I'm in the gallery.

Also  - there's a problem with the amount of dots in the page controller - if there are too many they just go off the screen.

**Comment by justinvallely** [comment]
Try removing this line: `galleryView?.view.translatesAutoresizingMaskIntoConstraints = false`

I also suspect the problem may be in your `override func updateViewConstraints() {
    self.view.haveViewFilledBy((galleryView?.view)!)` block.

**Comment by Viktorfalkner** [comment]
That line just allows me to layout the gallery to take the full size of my
ViewController.

That way I can have your gallery, the X button to close it, and its
delegation inside one controller.

All I do in UpdateViewConstraints is make the gallery take up the full size
of the view

**Comment by justinvallely** [comment]
You don't need to do all that. The gallery already loads full screen and features a tap to close function (which you've implemented). Just load the gallery with `presentViewController(gallery, animated: true, completion: nil)`

**Comment by Viktorfalkner** [comment]
I was trying to handle the delegation within a separate viewcontroller, so
I could reuse it.

the Xbutton function I made myself. You have a built in X button close
method?

**Comment by justinvallely** [comment]
> I was trying to handle the delegation within a separate viewcontroller, so
I could reuse it.

I'm not sure what you mean by this. It's all re-usable. 

> the Xbutton function I made myself. You have a built in X button close
method?

I don't have an "X button", but a single tap on the image will close the gallery. I recommend you download the repo and play with the example workspace and check out the full example code listed on the main page of the git repo.

**Comment by Viktorfalkner** [comment]
I've tried all the things youve said.

basically, If I add the gallery as a subview, and dont even constraint it,
the picture itself is out of wack - once I switch my orientation

The cell is still the full size of the screen, but the image is floating
inside of it.

**Comment by Viktorfalkner** [comment]
What I mean is.

I put your gallery inside of another viewcontroller so that I could handle
the delegation for the controller within that viewcontroller. I also added
an X button inside of it so I could close it in a different way.

I havent changed gallery at all, all I did was add it as a subview to my
view.

**Comment by LunaCodeGirl** [comment]
@Viktorfalkner the way you're doing this really defeats the purpose of this Cocoapod. If you hijack the `SwiftPhotoGallery`'s view without adding the view controller to the navigation stack, the `SwiftPhotoGallery` will never have its `UIViewController` methods called. In particular, the mehtod
```swift
 public override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator)
```
Will never be called on `SwiftPhotoGallery`. If you really want to remove the view in this way, you're going to have to handle rotations and the like on your own.

I'd suggest, as an alternative approach, that you Subclass SwiftPhotoGallery, and add your close button in 

```swift
public override func viewDidLoad()
```

That way you'll allow `SwiftPhotoGallery` to properly handle rotations and other `UIViewController` lifecycle events, and you can add your custom interface objects.

**Comment by justinvallely** [comment]
Well said Luna. Thank you.

**Comment by justinvallely** [comment]
@Viktorfalkner I didn't see you were grabbing the SwiftPhotoGallery's view and adding that to your subview. As @LunaCodeGirl noted, the gallery is meant to be loaded via its View Controller. Since the problem here is isolated to your code and not SwiftPhotoGallery itself, I'm going to close this issue as resolved.

**Comment by rajathooja** [comment]
Excuse me, hello, I don't mean to intrude on a closed issue.

I am trying to add a "Share" button to the Photo Gallery and I liked @LunaCodeGirl 's answer of subclassing SwiftPhotoGallery, however attempting this results in the error: "cannot inherit from non-open class outside of its defining module"

Apparently Swift 3 introduced the 'open' versus 'public' access level as explained in this Stackoverflow [answer](https://stackoverflow.com/questions/39072300/xcode-8-cannot-inherit-from-non-open-class)

So, I tried to achieve my Share button with an Extension instead, but overriding viewDidLoad() in an Extension blocks the superclass viewDidLoad() from being called, even with super.viewDidLoad()

The result of using an Extension to add a share button to the photo gallery is that the Page Control Indicator and Tap to Dismiss Gesture are not functioning, because SwiftPhotoGallery.viewDidLoad() is not being called.

Alas, this is not a detrimental UI failure, seeing as I can add a Close button alongside the Share button. But the eye-catchiness of the Photo Gallery is extremely cheapened without the Page Indicator and Swipe/Tap To Close gesture animations. I guess I'll just replicate the behavior in my class or Extension, if possible, or try method swizzling as described at [NSHipster](http://nshipster.com/swift-objc-runtime/)

Please consider updating your package to the 'open' access level so that it may be subclassed as @LunaCodeGirl answered.

See code excerpts,
(it doesn't matter where super.viewDidLoad() is in the method, it never gets called-- I added print() statements to SwiftPhotoGallery.viewDidLoad() to check)

```
extension SwiftPhotoGallery {
    
    public override func viewDidLoad() {
        //super.viewDidLoad()
        
        // create the share button
        let shareButton: UIButton! = UIButton(type: .custom)
        
        // configure the share button
        var buttonImage: UIImage!
        let buttonTintColor: UIColor = UIColor.white
        buttonImage = UIImage(named: "share-alt")?.withRenderingMode(.alwaysTemplate)
        shareButton.setImage(buttonImage, for: .normal)
        shareButton.tintColor = buttonTintColor
        
        shareButton.translatesAutoresizingMaskIntoConstraints = false
        
        var shareButtonConstraints: [NSLayoutConstraint] = []
        
        shareButtonConstraints.append(NSLayoutConstraint(item: shareButton,
                                                         attribute: .top,
                                                         relatedBy: .equal,
                                                         toItem: view,
                                                         attribute: .top,
                                                         multiplier: 1,
                                                         constant: 20))
        
        shareButtonConstraints.append(NSLayoutConstraint(item: shareButton,
                                                         attribute: .trailing,
                                                         relatedBy: .equal,
                                                         toItem: view,
                                                         attribute: .trailing,
                                                         multiplier: 1,
                                                         constant: -16))
        
        shareButtonConstraints.append(NSLayoutConstraint(item: shareButton,
                                                          attribute: .height,
                                                          relatedBy: .equal,
                                                          toItem: nil,
                                                          attribute: .notAnAttribute,
                                                          multiplier: 1,
                                                          constant: 25))
        
        shareButtonConstraints.append(NSLayoutConstraint(item: shareButton,
                                                         attribute: .width,
                                                         relatedBy: .equal,
                                                         toItem: nil,
                                                         attribute: .notAnAttribute,
                                                         multiplier: 1,
                                                         constant: 25))
        
        // Add the share button to the view.
        view.addSubview(shareButton)
        view.addConstraints(shareButtonConstraints)
        view.insertSubview(shareButton, aboveSubview: imageCollectionView)
        
        shareButton.addTarget(self, action: #selector(self.shareButtonClicked(_:)), for: .touchUpInside)
        super.viewDidLoad()
    }
```
