### ISSUE TITLE
Gallery picture position

### ISSUE THREAD

**Issue by HalitGumus** [justinvallely/SwiftPhotoGallery#46]
Hi,
How do we start the gallery from the selected picture ?

**Comment by justinvallely** [comment]
`present(gallery, animated: false, completion: { () -> Void in
    gallery.currentPage = 2
})`

**Comment by HalitGumus** [comment]
Thank you so much for your reply 😊

**Comment by Kamilton** [comment]
Why doesn't it work when I set gallery.currentPage line before presenting the gallery?  IMHO it should be working like that. However it works when I present gallery for second and other times for some reason
