### ISSUE TITLE
i can't get the images to zoom

### ISSUE THREAD

**Issue by aliaziada** [justinvallely/SwiftPhotoGallery#49]
when i try to zoom my images they start zooming only to bounce back to their original size and double tap won't work i installed the example and tried it the first two images zooms perfectly  but the last one have the same issue as mine 
here is my code

```
func openGallery(_ btn: UIButton){
        let gallery = SwiftPhotoGallery(delegate: self, dataSource: self)
        
        gallery.backgroundColor = UIColor.black
        gallery.pageIndicatorTintColor = UIColor.gray.withAlphaComponent(0.5)
        gallery.currentPageIndicatorTintColor = UIColor.white
        present(gallery, animated: false) {
            gallery.currentPage = btn.tag;
        }
        
    }

extension CarInfoVC: SwiftPhotoGalleryDataSource, SwiftPhotoGalleryDelegate {
    func numberOfImagesInGallery(gallery: SwiftPhotoGallery) -> Int {
        return imgArr.count
    }
    
    func imageInGallery(gallery: SwiftPhotoGallery, forIndex: Int) -> UIImage? {
        
        return UIImage(named: imgArr[forIndex])
    }
    
    // MARK: SwiftPhotoGalleryDelegate Methods
    
    func galleryDidTapToClose(gallery: SwiftPhotoGallery) {
        dismiss(animated: true, completion: nil)
    }
}
```

**Comment by justinvallely** [comment]
Hello. You need larger images. I left the 3rd image in the example small on purpose to demonstrate this behavior.

**Comment by aliaziada** [comment]
is there a way to solve this without using larger images as the images comes from a server and i can't control its size

**Comment by justinvallely** [comment]
Yes, but in doing so you'd be zooming an image past its native size where it would appear blurry. Or you could just use an older device with lower resolution.

**Comment by LunaCodeGirl** [comment]
Maybe we could expose a `maximumZoomScale` property that just passes it through to the `scrollView`? Or just make the `scrollView` public instead of private, so people could just set this value themselves. That would certainly allow consumers to manipulate the behavior without needing to fork and modify SwiftPhotoGallery themselves.

**Comment by aliaziada** [comment]
thanks a lot for your answer
