### ISSUE TITLE
When using transitioningDelegate, a non-responsive black screen appears

### ISSUE THREAD

**Issue by rajathooja** [justinvallely/SwiftPhotoGallery#56]
I tried using your example of the transitioningDelegate as you have it with the Custom Transitions classes (DimmingPresentationController, PresentingAnimator, DismissingAnimator) and a black screen appears when a gallery item is selected.

I even code-dumped the example project into mine (except for images) and got a black screen.
![fbbs6vtfir](https://user-images.githubusercontent.com/30729195/29960107-ef64919e-8f17-11e7-9db8-cb5fe78aa6ad.gif)

**Comment by rajathooja** [comment]
i set the animated: bool to 'false' so that it at least displays photographs properly.

`// MARK: - UICollectionViewDelegate
    
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
        index = indexPath.item
        
        let gallery = SwiftPhotoGallery(delegate: self, dataSource: self)
        
        gallery.backgroundColor = UIColor.black
        gallery.pageIndicatorTintColor = UIColor.gray.withAlphaComponent(0.5)
        gallery.currentPageIndicatorTintColor = appDelegate.globalThemeColor
        gallery.hidePageControl = false
        gallery.modalPresentationStyle = .custom
        
        // transition animations not working
        //gallery.transitioningDelegate = self
        
        // load photo viewer on selected image
        present(gallery, animated: false, completion: { () -> Void in
            gallery.currentPage = self.index
        })
    }`

**Comment by kylebegeman** [comment]
@rajathooja Did you resolve this, and if so, how?
