### ISSUE TITLE
Page controller off by 1 when setting currentPage after presenting

### ISSUE THREAD

**Issue by ghost** [justinvallely/SwiftPhotoGallery#69]
By using the README recommended code to navigate to a specific page:

```
present(gallery, animated: true, completion: { () -> Void in
    gallery.currentPage = self.index
})
```

the result is that the images in the array do not match the index of the `pageControl`. There is some sort of race condition with presenting the view controller, setting the `pageControl.currentPage`, and setting `currentPage`.

**Comment by ghost** [comment]
The problem is in `viewDidAppear`. The `currentPage` always begins at `-1`, so even if I'm presenting the gallery and going to set the `currentPage` to the index of my array, the `viewDidAppear` method detects that `currentPage` is `< 0`, and sets `currentPage` to `0` which fires `updatePageControl` and sets the `pageControl`'s `currentPage` to `0` as well.

**Comment by ghost** [comment]
The `currentPage` and `updatePageControl` are called after the above, but don't take affect.

**Comment by justinvallely** [comment]
@seanperez29 Would you mind taking a look at your code involving this?

**Comment by ghost** [comment]
Initializing currentPage with 0 seems to help, but since the getter is overridden, you can’t initialize the value to 0. I’m wondering if having the getter and setter of currentPage be so involved with the UI is not a good design pattern.

**Comment by justinvallely** [comment]
@mpatzer Can you share more details of your error please? We're not seeing any issues with either the sample application, our commercial uses, or unit tests.

If you have a better design pattern, I'd be happy to take a look at a Pull Request from you. We're always open to outside submittals.

**Comment by ghost** [comment]
@justinvallely I'll see if I can reproduce with a minimal app. I just tried the sample app and cannot reproduce the issue I had, so I'll have to isolate the cause in my setup. If there is an issue and I find a solution, I'll submit a PR. Did you see my PR for Swift 4 projects? #68

**Comment by ghost** [comment]
Looking at the sample app, I'm remembering I used `indexPath.row` instead of `indexPath.item` to provide the `index` for the `currentPage` for my collection view. I can verify when I'm home, but that must be it. I'll go ahead and close this issue.

**Comment by justinvallely** [comment]
@mpatzer I did see that Swift 4 PR, but didn't realize if was from you. Thank you for doing that. Hoping to get that merged in soon. 

We're seeing other issues with Swift 4 that may be related to what you're seeing here. Did you run a swift 4 conversion on your fork of SwiftPhotoGallery? That could be why you're seeing the index off by 1 error, yet the example code (as swift 3) works fine.
