### ISSUE TITLE
Swift 4 Gallery page index

### ISSUE THREAD

**Issue by crowell256aa** [justinvallely/SwiftPhotoGallery#70]
I'm using this in a vanilla way in a Swift 4 project.   (I've already incorporated mpatzer's fix of the Swift 4 issue related to instance methods not be exposed to Objective C by re-using his solution.)

The example I'm working with has a three photo gallery.  

When you open the gallery, the current page indicator (the dots) is correct, and the first dot is bold, as expected.  When you advance one photo, the highlighted dot does not change, but the photo does.  Another swipe advances to the third photo, and the second dot is highlighted (one behind what it should be).  No further swiping in that direction is allowed.

Going back in the other direction from the furthest point, the second picture in the series is shown, and the *first* dot highlighted.  Another swipe in that direction, and then surprisingly, the third photo is shown and the middle dot highlighted.  You can no longer swipe to the first photo.

Hoping this is some simple array indexing issue related to Swift 4.  The library is very simple and clean and dead simple to implement.  It's was a pleasure to implement.

Also...and I am sorry if this isn't the right place... but do you have any guidance on implementing a caption for each photo?

**Comment by justinvallely** [comment]
This should be fixed in the latest version (3.3.0). Please check and re-open if it's still an issue.
