### ISSUE TITLE
crash when rotating in Swift 4

### ISSUE THREAD

**Issue by TeeAche** [justinvallely/SwiftPhotoGallery#71]
Hello,

When rotating my dev iPhone I get a EXC_BAD_ACCESS from line 153 in SwiftPhotoGallery.swift

`            imageCollectionView.reloadItems(at: [desiredIndexPath])`

**Comment by justinvallely** [comment]
This should be fixed in the latest version (3.3.0). Please check and re-open if it's still an issue.
