### ISSUE TITLE
Is there any way to add information to the picture ? 

### ISSUE THREAD

**Issue by rollin-s** [justinvallely/SwiftPhotoGallery#75]
Hello, 
I started to use your library (which is great !) and I have to add some informations like the picture name, a button, and other stuff to the image.

Do you have any tracks so I can begin to do that ? Have you done anything to make that easier ?
I looked inside your code, and I found that this is the cell that are the pictures, so I could have to overdrive some of your methods to make that I want (juste the picture name displayed for exemple !)

**Comment by justinvallely** [comment]
Yes, you can override the views as needed. Picture name/caption is a duplicate feature request of Issue #74 . Closing this one.
