### ISSUE TITLE
Image download from Url

### ISSUE THREAD

**Issue by nikhil191090** [justinvallely/SwiftPhotoGallery#78]
Hello . first of all you have created great library swiftphotogalley. I am downloading images from url and those images  I want to show on collectionview . please do help.

**Comment by zhouhao27** [comment]
You can't do asyn call through `func imageInGallery(gallery: SwiftPhotoGallery, forIndex: Int) -> UIImage? ` .

I think the only way is to add one more method in data source to pass a cell like what UICollectionView data source did. Then you can load image asynchronously.

For example, I add one method in datasource, then change the getImage like this:

```
  fileprivate func getImage(currentPage: Int, complete: @escaping (UIImage?)->()) {
    dataSource?.loadImage(forGallery: self, at: currentPage, complete: complete)
  }

```

In collection view datasource:

```
      cell.image = nil
      getImage(currentPage: indexPath.row) { (image) in
        cell.image = image
      }

```

**Comment by zhouhao27** [comment]
You can check my sample:

https://github.com/zhouhao27/WOWGallery
