### ISSUE TITLE
Rotation bug when going from portrait to Landscape on 1st image

### ISSUE THREAD

**Issue by marcvanolmen** [justinvallely/SwiftPhotoGallery#79]
I tried out the example that is included. on iPHone 6,7,8 I tested it. 

1. When in full screen mode (tap on one of the images)
2. When you have first photo up 
3.  When going from Portrait to Landscape there are  2 photos. being displayed during rotation.

**Comment by justinvallely** [comment]
This is how UICollectionView reloads cells. Some call it a bug, some call it a feature. ¯\_(ツ)_/¯

**Comment by marcvanolmen** [comment]
But there are different photos being displayed, I doubt it is a feature...

**Comment by marcvanolmen** [comment]
By the way this Apple Sample Code doesn't have that issue:

https://developer.apple.com/library/content/samplecode/PhotoTransitioning/Listings/Photo_Transitioning_AssetTransitionDriver_swift.html

as far as we can see these are the key differences compared to your  code:

1. the UICollectionView  as the root view (because it uses UICollectionViewController) is the key to avoid this issue.
2. Also it does some manual setting of the itemsize on the flowLayout 
3. also the function targetContentOffsetForProposedContentOffset offset calculation is key.
