### ISSUE TITLE
iOS 12 Image jump right-down

### ISSUE THREAD

**Issue by xvicient21** [justinvallely/SwiftPhotoGallery#84]
Hi,

Only with iOS 12, the image loaded moves down and right after less than a second. I have attached an example:
<div style="display:inline-block; width:100%;">
<img style="display: inline" width="150" alt="1" src="https://user-images.githubusercontent.com/37865245/41843737-97136f9c-786e-11e8-8a2d-817fd5ecee98.png">
<img style="display: inline" width="150" alt="2" src="https://user-images.githubusercontent.com/37865245/41843738-9745acd2-786e-11e8-9028-62c5262e4d90.png">
</div>

I'm working to find and fix this issue. @Inspirato, do you have any idea what is happening?

Thanks!

**Comment by alexpeman21b** [comment]
@inspirato @victorfoster any idea about this issue?

**Comment by justinvallely** [comment]
Can you confirm this happens with the example project packaged with the cocoapod? I’m not seeing any issues in iOS 12.
