### ISSUE TITLE
Images with url not working for this library

### ISSUE THREAD

**Issue by ahmed-sharief5** [justinvallely/SwiftPhotoGallery#85]
I am appending images from an api which gives me the url. I tried appending url process for UIImage but its not working. Can you please tell me how to do that

**Comment by razone** [comment]
I had this issue also. What I did was retrieve the image data after loading the image via url and then add it to an array of images. I then work with the array of images.

**Comment by ShaybazSayyed313** [comment]
I m using the same library for gallery its working fine for static images .but when i m getting image from  Server in url form how to assign this url.Get stuck please provide me the solution.

**Comment by pmiotto** [comment]
Same issue. It seems that this library does not integrate seamlessly with SDWebImage as it claims.
